### ISSUE TITLE
 Approved access to the API but problems with permissions

### ISSUE THREAD

**Issue by manublogsterapp** [abarron-linkedin/abarron-linkedinRepo0829174934#1]
Hi Abarron :)

We have various problems and are the following:

We received this communication:

_LinkedIn Marketing Analytics API Access Approved
Prospective LinkedIn Marketing Developer,
Thank you for your interest in joining our Marketing Developer Program - your application for Audience Management and Marketing Analytics APIs has been reviewed. 
We are happy to share that your request for Marketing Analytics APIs has been approved. As such, the API key(s) you included in your application have been provisioned with Marketing Analytics API access and you may now begin leveraging these APIs in accordance with our Marketing Developer Program Terms.
Conversely, we are not able to approve your request for Audience Management capabilities at this time.
Best of luck in your integration efforts._

**We work correctly with the following permissions:**
r_liteprofile + w_member_social

**We have problems with the following permissions:**
r_member_social
rw_organization_admin
w_organization_social
r_organization_social

Where is error? Why do not we have access to those permissions if we have approved the _LinkedIn Marketing Analytics API?

Thanks in advance

**Comment by manublogsterapp** [comment]
Hi @abarron-linkedin :)

Can you help us?

Thank you

**Comment by abarron-linkedin** [comment]
@manublogsterapp Happy to help, but can you please file a Zendesk ticket with your question here: https://linkedin.zendesk.com/hc/en-us/requests/new?ticket_form_id=360000203132
